version: "3.8"
services:
  java_app:
    container_name: java_app
    image: dannyhs/propiedades:1d6f865833371f26544db1f0bf27c4
    build: .
    ports:
      - 8083:8080
    environment:
      - DATA_BASE_URL=jdbc:postgresql://db-postgresql-nyc3-79796-do-user-15512334-0.c.db.ondigitalocean.com:25060/nurairbnbc
      - DATA_BASE_USERNAME=doadmin
      - DATA_BASE_PASSWORD=AVNS_0wmhCcsag4WsAFG6qB0
      - PORT=8083
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Estudiar1995
      POSTGRES_DB: nurairbnbc

networks:
  nurbnbcristhian:
    driver: bridge