spring.application.name: propiedades
server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DATA_BASE_URL:jdbc:postgresql://db-postgresql-nyc3-79796-do-user-15512334-0.c.db.ondigitalocean.com:25060/nurairbnbc}
    username: ${DATA_BASE_USERNAME:doadmin}
    password: ${DATA_BASE_PASSWORD:AVNS_0wmhCcsag4WsAFG6qB0}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /

